# 使用 Node.js 18 作为基础镜像
FROM node:18

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 pnpm-lock.yaml 文件以进行依赖安装
COPY package.json pnpm-lock.yaml /app/

# 安装 pnpm
RUN npm install -g pnpm
# 安装项目依赖
RUN pnpm install --production

# 复制构建后的应用程序到容器中
COPY . /app
# 暴露应用运行的端口
EXPOSE 3000

# 启动应用
CMD ["pnpm", "start"]